-- MySQL Script generated by MySQL Workbench
-- ter 24 out 2017 12:48:23 -02
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema SGE
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `SGE` ;

-- -----------------------------------------------------
-- Schema SGE
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `SGE` DEFAULT CHARACTER SET utf8 ;
USE `SGE` ;

-- -----------------------------------------------------
-- Table `SGE`.`sge_cursos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SGE`.`sge_cursos` ;

CREATE TABLE IF NOT EXISTS `SGE`.`sge_cursos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `sigla` VARCHAR(45) NOT NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  `salvoPor` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_cursos_usuarios1_idx` (`salvoPor` ASC),
  CONSTRAINT `fk_cursos_usuarios1`
    FOREIGN KEY (`salvoPor`)
    REFERENCES `SGE`.`sge_usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SGE`.`sge_usuarios_tipos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SGE`.`sge_usuarios_tipos` ;

CREATE TABLE IF NOT EXISTS `SGE`.`sge_usuarios_tipos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  `salvoPor` INT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nome_UNIQUE` (`nome` ASC),
  INDEX `fk_usuarios_tipos_usuarios1_idx` (`salvoPor` ASC),
  CONSTRAINT `fk_usuarios_tipos_usuarios1`
    FOREIGN KEY (`salvoPor`)
    REFERENCES `SGE`.`sge_usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SGE`.`sge_usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SGE`.`sge_usuarios` ;

CREATE TABLE IF NOT EXISTS `SGE`.`sge_usuarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idCursos` INT NULL,
  `idUsuariosTipos` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `dataNascimento` DATE NOT NULL,
  `login` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(60) NOT NULL,
  `remember_token` VARCHAR(100) NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_usuarios_curso1_idx` (`idCursos` ASC),
  INDEX `fk_usuarios_usuarios_tipos1_idx` (`idUsuariosTipos` ASC),
  CONSTRAINT `fk_usuarios_curso1`
    FOREIGN KEY (`idCursos`)
    REFERENCES `SGE`.`sge_cursos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuarios_usuarios_tipos1`
    FOREIGN KEY (`idUsuariosTipos`)
    REFERENCES `SGE`.`sge_usuarios_tipos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SGE`.`sge_eventos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SGE`.`sge_eventos` ;

CREATE TABLE IF NOT EXISTS `SGE`.`sge_eventos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idEdicaoAnterior` INT NULL,
  `idPai` INT NULL,
  `titulo` VARCHAR(255) NULL,
  `nome` VARCHAR(150) NOT NULL,
  `nomeSlug` VARCHAR(200) NOT NULL,
  `dataInicioInscricao` DATETIME NOT NULL,
  `dataFimInscricao` DATETIME NOT NULL,
  `dataInicio` DATETIME NOT NULL,
  `dataTermino` DATETIME NOT NULL,
  `descricao` LONGTEXT NOT NULL,
  `comissaoOrganizadora` TEXT NULL,
  `publicoAlvo` VARCHAR(255) NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  `salvoPor` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_eventos_eventos1_idx` (`idPai` ASC),
  INDEX `fk_eventos_eventos2_idx` (`idEdicaoAnterior` ASC),
  INDEX `fk_eventos_usuarios1_idx` (`salvoPor` ASC),
  UNIQUE INDEX `nome_UNIQUE` (`nome` ASC),
  UNIQUE INDEX `nomeSlug_UNIQUE` (`nomeSlug` ASC),
  CONSTRAINT `fk_eventos_eventos1`
    FOREIGN KEY (`idPai`)
    REFERENCES `SGE`.`sge_eventos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_eventos_eventos2`
    FOREIGN KEY (`idEdicaoAnterior`)
    REFERENCES `SGE`.`sge_eventos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_eventos_usuarios1`
    FOREIGN KEY (`salvoPor`)
    REFERENCES `SGE`.`sge_usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SGE`.`sge_atividades_tipos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SGE`.`sge_atividades_tipos` ;

CREATE TABLE IF NOT EXISTS `SGE`.`sge_atividades_tipos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  `salvoPor` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_atividades_tipos_usuarios1_idx` (`salvoPor` ASC),
  CONSTRAINT `fk_atividades_tipos_usuarios1`
    FOREIGN KEY (`salvoPor`)
    REFERENCES `SGE`.`sge_usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SGE`.`sge_unidades`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SGE`.`sge_unidades` ;

CREATE TABLE IF NOT EXISTS `SGE`.`sge_unidades` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(60) NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  `salvoPor` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_sge_unidades_sge_usuarios1_idx` (`salvoPor` ASC),
  CONSTRAINT `fk_sge_unidades_sge_usuarios1`
    FOREIGN KEY (`salvoPor`)
    REFERENCES `SGE`.`sge_usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SGE`.`sge_locais`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SGE`.`sge_locais` ;

CREATE TABLE IF NOT EXISTS `SGE`.`sge_locais` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idUnidades` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  `salvoPor` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_locais_usuarios1_idx` (`salvoPor` ASC),
  INDEX `fk_sge_locais_sge_unidades1_idx` (`idUnidades` ASC),
  CONSTRAINT `fk_locais_usuarios1`
    FOREIGN KEY (`salvoPor`)
    REFERENCES `SGE`.`sge_usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sge_locais_sge_unidades1`
    FOREIGN KEY (`idUnidades`)
    REFERENCES `SGE`.`sge_unidades` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SGE`.`sge_espacos_tipos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SGE`.`sge_espacos_tipos` ;

CREATE TABLE IF NOT EXISTS `SGE`.`sge_espacos_tipos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  `sge_usuarios_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_sge_espacos_tipos_sge_usuarios1_idx` (`sge_usuarios_id` ASC),
  CONSTRAINT `fk_sge_espacos_tipos_sge_usuarios1`
    FOREIGN KEY (`sge_usuarios_id`)
    REFERENCES `SGE`.`sge_usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SGE`.`sge_salas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SGE`.`sge_salas` ;

CREATE TABLE IF NOT EXISTS `SGE`.`sge_salas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idLocais` INT NOT NULL,
  `idEspacosTipos` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `quantidade_ocupacao` INT NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  `salvoPor` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_salas_locais1_idx` (`idLocais` ASC),
  INDEX `fk_sge_salas_sge_usuarios1_idx` (`salvoPor` ASC),
  INDEX `fk_sge_salas_sge_espacos_tipos1_idx` (`idEspacosTipos` ASC),
  CONSTRAINT `fk_salas_locais1`
    FOREIGN KEY (`idLocais`)
    REFERENCES `SGE`.`sge_locais` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sge_salas_sge_usuarios1`
    FOREIGN KEY (`salvoPor`)
    REFERENCES `SGE`.`sge_usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sge_salas_sge_espacos_tipos1`
    FOREIGN KEY (`idEspacosTipos`)
    REFERENCES `SGE`.`sge_espacos_tipos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SGE`.`sge_atividades`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SGE`.`sge_atividades` ;

CREATE TABLE IF NOT EXISTS `SGE`.`sge_atividades` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idEventos` INT NOT NULL,
  `idAtividadesTipos` INT NOT NULL,
  `idUnidades` INT NULL,
  `idLocais` INT NULL,
  `idSalas` INT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `quantidadeVagas` INT NULL,
  `descricao` LONGTEXT NULL,
  `comentario` TEXT NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  `salvoPor` INT NULL,
  `sge_atividadescol` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_atividades_eventos_idx` (`idEventos` ASC),
  INDEX `fk_atividades_atividades_tipos1_idx` (`idAtividadesTipos` ASC),
  INDEX `fk_atividades_usuarios1_idx` (`salvoPor` ASC),
  INDEX `fk_sge_atividades_sge_salas1_idx` (`idSalas` ASC),
  INDEX `fk_sge_atividades_sge_locais1_idx` (`idLocais` ASC),
  INDEX `fk_sge_atividades_sge_unidades1_idx` (`idUnidades` ASC),
  CONSTRAINT `fk_atividades_eventos`
    FOREIGN KEY (`idEventos`)
    REFERENCES `SGE`.`sge_eventos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_atividades_atividades_tipos1`
    FOREIGN KEY (`idAtividadesTipos`)
    REFERENCES `SGE`.`sge_atividades_tipos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_atividades_usuarios1`
    FOREIGN KEY (`salvoPor`)
    REFERENCES `SGE`.`sge_usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sge_atividades_sge_salas1`
    FOREIGN KEY (`idSalas`)
    REFERENCES `SGE`.`sge_salas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sge_atividades_sge_locais1`
    FOREIGN KEY (`idLocais`)
    REFERENCES `SGE`.`sge_locais` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sge_atividades_sge_unidades1`
    FOREIGN KEY (`idUnidades`)
    REFERENCES `SGE`.`sge_unidades` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SGE`.`sge_atividades_datas_horas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SGE`.`sge_atividades_datas_horas` ;

CREATE TABLE IF NOT EXISTS `SGE`.`sge_atividades_datas_horas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idAtividades` INT NOT NULL,
  `data` DATE NOT NULL,
  `horarioInicio` TIME(0) NOT NULL,
  `horarioTermino` TIME(0) NOT NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  `salvoPor` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_atividadeHorario_atividades1_idx` (`idAtividades` ASC),
  INDEX `fk_atividades_datas_usuarios1_idx` (`salvoPor` ASC),
  CONSTRAINT `fk_atividadeHorario_atividades1`
    FOREIGN KEY (`idAtividades`)
    REFERENCES `SGE`.`sge_atividades` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_atividades_datas_usuarios1`
    FOREIGN KEY (`salvoPor`)
    REFERENCES `SGE`.`sge_usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SGE`.`sge_atividades_participantes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SGE`.`sge_atividades_participantes` ;

CREATE TABLE IF NOT EXISTS `SGE`.`sge_atividades_participantes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idAtividades` INT NOT NULL,
  `idUsuarios` INT NOT NULL,
  `presenca` TINYINT(1) NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  `salvoPor` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_atividades_has_participantes_atividades1_idx` (`idAtividades` ASC),
  INDEX `fk_atividades_participantes_usuarios1_idx` (`idUsuarios` ASC),
  INDEX `fk_atividades_participantes_usuarios2_idx` (`salvoPor` ASC),
  CONSTRAINT `fk_atividades_has_participantes_atividades1`
    FOREIGN KEY (`idAtividades`)
    REFERENCES `SGE`.`sge_atividades` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_atividades_participantes_usuarios1`
    FOREIGN KEY (`idUsuarios`)
    REFERENCES `SGE`.`sge_usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_atividades_participantes_usuarios2`
    FOREIGN KEY (`salvoPor`)
    REFERENCES `SGE`.`sge_usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SGE`.`sge_atividades_cursos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SGE`.`sge_atividades_cursos` ;

CREATE TABLE IF NOT EXISTS `SGE`.`sge_atividades_cursos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idCursos` INT NOT NULL,
  `idAtividades` INT NOT NULL,
  `dataInicio` DATE NULL,
  `dataFim` DATE NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  `salvoPor` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_atividades_has_cursos_cursos1_idx` (`idCursos` ASC),
  INDEX `fk_atividades_has_cursos_atividades1_idx` (`idAtividades` ASC),
  INDEX `fk_atividades_cursos_usuarios1_idx` (`salvoPor` ASC),
  CONSTRAINT `fk_atividades_has_cursos_atividades1`
    FOREIGN KEY (`idAtividades`)
    REFERENCES `SGE`.`sge_atividades` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_atividades_has_cursos_cursos1`
    FOREIGN KEY (`idCursos`)
    REFERENCES `SGE`.`sge_cursos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_atividades_cursos_usuarios1`
    FOREIGN KEY (`salvoPor`)
    REFERENCES `SGE`.`sge_usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SGE`.`sge_atividades_status`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SGE`.`sge_atividades_status` ;

CREATE TABLE IF NOT EXISTS `SGE`.`sge_atividades_status` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  `salvoPor` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_atividades_status_usuarios1_idx` (`salvoPor` ASC),
  CONSTRAINT `fk_atividades_status_usuarios1`
    FOREIGN KEY (`salvoPor`)
    REFERENCES `SGE`.`sge_usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SGE`.`sge_atividades_atividades_status`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SGE`.`sge_atividades_atividades_status` ;

CREATE TABLE IF NOT EXISTS `SGE`.`sge_atividades_atividades_status` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idAtividades` INT NOT NULL,
  `idAtividadesStatus` INT NOT NULL,
  `observacao` VARCHAR(255) NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  `salvoPor` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_atividades_has_atividades_status_atividades_status1_idx` (`idAtividadesStatus` ASC),
  INDEX `fk_atividades_has_atividades_status_atividades1_idx` (`idAtividades` ASC),
  INDEX `fk_atividades_atividades_status_usuarios1_idx` (`salvoPor` ASC),
  CONSTRAINT `fk_atividades_has_atividades_status_atividades1`
    FOREIGN KEY (`idAtividades`)
    REFERENCES `SGE`.`sge_atividades` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_atividades_has_atividades_status_atividades_status1`
    FOREIGN KEY (`idAtividadesStatus`)
    REFERENCES `SGE`.`sge_atividades_status` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_atividades_atividades_status_usuarios1`
    FOREIGN KEY (`salvoPor`)
    REFERENCES `SGE`.`sge_usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SGE`.`sge_usuarios_grupos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SGE`.`sge_usuarios_grupos` ;

CREATE TABLE IF NOT EXISTS `SGE`.`sge_usuarios_grupos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  `salvoPor` INT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nome_UNIQUE` (`nome` ASC),
  INDEX `fk_usuarios_grupos_usuarios1_idx` (`salvoPor` ASC),
  CONSTRAINT `fk_usuarios_grupos_usuarios1`
    FOREIGN KEY (`salvoPor`)
    REFERENCES `SGE`.`sge_usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SGE`.`sge_aparencias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SGE`.`sge_aparencias` ;

CREATE TABLE IF NOT EXISTS `SGE`.`sge_aparencias` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tema` VARCHAR(45) NOT NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  `salvoPor` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_aparencias_usuarios1_idx` (`salvoPor` ASC),
  CONSTRAINT `fk_aparencias_usuarios1`
    FOREIGN KEY (`salvoPor`)
    REFERENCES `SGE`.`sge_usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SGE`.`sge_eventos_caracteristicas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SGE`.`sge_eventos_caracteristicas` ;

CREATE TABLE IF NOT EXISTS `SGE`.`sge_eventos_caracteristicas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idAparencias` INT NOT NULL,
  `idEventos` INT NOT NULL,
  `eImagemDeFundo` TINYINT(1) NULL,
  `background` VARCHAR(45) NULL,
  `backgroundColor` VARCHAR(45) NULL,
  `eEmiteCertificado` TINYINT(1) NOT NULL,
  `dataLiberacaoCertificado` DATE NULL,
  `eExistemImagens` TINYINT(1) NULL,
  `eExistemNoticias` VARCHAR(45) NULL,
  `favicon` VARCHAR(45) NULL,
  `logo` VARCHAR(45) NULL,
  `ePropostaAtividade` TINYINT(1) NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  `salvoPor` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_eventos_configuracoes_aparencias1_idx` (`idAparencias` ASC),
  INDEX `fk_eventos_caracteristicas_usuarios1_idx` (`salvoPor` ASC),
  INDEX `fk_eventos_caracteristicas_eventos1_idx` (`idEventos` ASC),
  CONSTRAINT `fk_eventos_configuracoes_aparencias1`
    FOREIGN KEY (`idAparencias`)
    REFERENCES `SGE`.`sge_aparencias` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_eventos_caracteristicas_usuarios1`
    FOREIGN KEY (`salvoPor`)
    REFERENCES `SGE`.`sge_usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_eventos_caracteristicas_eventos1`
    FOREIGN KEY (`idEventos`)
    REFERENCES `SGE`.`sge_eventos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SGE`.`sge_eventos_usuarios_tipos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SGE`.`sge_eventos_usuarios_tipos` ;

CREATE TABLE IF NOT EXISTS `SGE`.`sge_eventos_usuarios_tipos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idEventos` INT NOT NULL,
  `idUsuariosTipos` INT NOT NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  `salvoPor` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_usuarios_tipos_has_eventos_eventos1_idx` (`idEventos` ASC),
  INDEX `fk_usuarios_tipos_has_eventos_usuarios_tipos1_idx` (`idUsuariosTipos` ASC),
  INDEX `fk_eventos_usuarios_tipos_usuarios1_idx` (`salvoPor` ASC),
  CONSTRAINT `fk_usuarios_tipos_has_eventos_usuarios_tipos1`
    FOREIGN KEY (`idUsuariosTipos`)
    REFERENCES `SGE`.`sge_usuarios_tipos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuarios_tipos_has_eventos_eventos1`
    FOREIGN KEY (`idEventos`)
    REFERENCES `SGE`.`sge_eventos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_eventos_usuarios_tipos_usuarios1`
    FOREIGN KEY (`salvoPor`)
    REFERENCES `SGE`.`sge_usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SGE`.`sge_eventos_imagens`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SGE`.`sge_eventos_imagens` ;

CREATE TABLE IF NOT EXISTS `SGE`.`sge_eventos_imagens` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idEventos` INT NOT NULL,
  `imagem` VARCHAR(128) NOT NULL,
  `thumbnail` VARCHAR(128) NULL,
  `dataDaImagem` DATE NULL,
  `descricao` TEXT NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  `salvoPor` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_eventos_galerias_eventos1_idx` (`idEventos` ASC),
  INDEX `fk_eventos_imagens_usuarios1_idx` (`salvoPor` ASC),
  CONSTRAINT `fk_eventos_galerias_eventos1`
    FOREIGN KEY (`idEventos`)
    REFERENCES `SGE`.`sge_eventos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_eventos_imagens_usuarios1`
    FOREIGN KEY (`salvoPor`)
    REFERENCES `SGE`.`sge_usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SGE`.`sge_eventos_noticias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SGE`.`sge_eventos_noticias` ;

CREATE TABLE IF NOT EXISTS `SGE`.`sge_eventos_noticias` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idEventos` INT NOT NULL,
  `preview` VARCHAR(255) NOT NULL,
  `titulo` VARCHAR(45) NOT NULL,
  `noticia` LONGTEXT NOT NULL,
  `dataHoraPublicacao` DATETIME NOT NULL,
  `dataHoraInicio` DATETIME NULL,
  `dataHoraFim` DATETIME NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  `salvoPor` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_enventos_noticias_eventos1_idx` (`idEventos` ASC),
  INDEX `fk_enventos_noticias_usuarios1_idx` (`salvoPor` ASC),
  CONSTRAINT `fk_enventos_noticias_eventos1`
    FOREIGN KEY (`idEventos`)
    REFERENCES `SGE`.`sge_eventos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_enventos_noticias_usuarios1`
    FOREIGN KEY (`salvoPor`)
    REFERENCES `SGE`.`sge_usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SGE`.`sge_eventos_contatos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SGE`.`sge_eventos_contatos` ;

CREATE TABLE IF NOT EXISTS `SGE`.`sge_eventos_contatos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `telefone` VARCHAR(45) NULL,
  `celular` VARCHAR(45) NULL,
  `email` VARCHAR(100) NOT NULL,
  `redesSociais` VARCHAR(200) NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  `salvoPor` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_eventos_contatos_usuarios1_idx` (`salvoPor` ASC),
  CONSTRAINT `fk_eventos_contatos_usuarios1`
    FOREIGN KEY (`salvoPor`)
    REFERENCES `SGE`.`sge_usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SGE`.`sge_atividades_responsaveis`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SGE`.`sge_atividades_responsaveis` ;

CREATE TABLE IF NOT EXISTS `SGE`.`sge_atividades_responsaveis` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idAtividades` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `titulacao` VARCHAR(45) NULL,
  `instituicaoOrigem` VARCHAR(45) NULL,
  `experienciaProfissional` TEXT NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  `salvoPor` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_atividades_responsaveis_atividades1_idx` (`idAtividades` ASC),
  INDEX `fk_atividades_responsaveis_usuarios1_idx` (`salvoPor` ASC),
  CONSTRAINT `fk_atividades_responsaveis_atividades1`
    FOREIGN KEY (`idAtividades`)
    REFERENCES `SGE`.`sge_atividades` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_atividades_responsaveis_usuarios1`
    FOREIGN KEY (`salvoPor`)
    REFERENCES `SGE`.`sge_usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SGE`.`sge_contatos_eventos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SGE`.`sge_contatos_eventos` ;

CREATE TABLE IF NOT EXISTS `SGE`.`sge_contatos_eventos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idEventosContatos` INT NOT NULL,
  `idEventos` INT NOT NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  `salvoPor` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_eventos_contatos_has_eventos_eventos1_idx` (`idEventos` ASC),
  INDEX `fk_eventos_contatos_has_eventos_eventos_contatos1_idx` (`idEventosContatos` ASC),
  INDEX `fk_contatos_eventos_usuarios1_idx` (`salvoPor` ASC),
  CONSTRAINT `fk_eventos_contatos_has_eventos_eventos_contatos1`
    FOREIGN KEY (`idEventosContatos`)
    REFERENCES `SGE`.`sge_eventos_contatos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_eventos_contatos_has_eventos_eventos1`
    FOREIGN KEY (`idEventos`)
    REFERENCES `SGE`.`sge_eventos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_contatos_eventos_usuarios1`
    FOREIGN KEY (`salvoPor`)
    REFERENCES `SGE`.`sge_usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SGE`.`sge_usuarios_usuarios_grupos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SGE`.`sge_usuarios_usuarios_grupos` ;

CREATE TABLE IF NOT EXISTS `SGE`.`sge_usuarios_usuarios_grupos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idUsuariosGrupos` INT NOT NULL,
  `idUsuarios` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_usuarios_grupos_has_usuarios_usuarios1_idx` (`idUsuarios` ASC),
  INDEX `fk_usuarios_grupos_has_usuarios_usuarios_grupos1_idx` (`idUsuariosGrupos` ASC),
  CONSTRAINT `fk_usuarios_grupos_has_usuarios_usuarios_grupos1`
    FOREIGN KEY (`idUsuariosGrupos`)
    REFERENCES `SGE`.`sge_usuarios_grupos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuarios_grupos_has_usuarios_usuarios1`
    FOREIGN KEY (`idUsuarios`)
    REFERENCES `SGE`.`sge_usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SGE`.`password_resets`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SGE`.`password_resets` ;

CREATE TABLE IF NOT EXISTS `SGE`.`password_resets` (
  `email` VARCHAR(60) NULL,
  `token` VARCHAR(45) NULL,
  `created_at` TIMESTAMP NULL,
  INDEX `fk_email` (`email` ASC),
  INDEX `fk_token` (`token` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SGE`.`sge_links_externos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SGE`.`sge_links_externos` ;

CREATE TABLE IF NOT EXISTS `SGE`.`sge_links_externos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idEventos` INT NOT NULL,
  `descricao` VARCHAR(45) NULL,
  `url` VARCHAR(60) NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  `salvoPor` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_links_externos_eventos1_idx` (`idEventos` ASC),
  INDEX `fk_sge_links_externos_sge_usuarios1_idx` (`salvoPor` ASC),
  CONSTRAINT `fk_links_externos_eventos1`
    FOREIGN KEY (`idEventos`)
    REFERENCES `SGE`.`sge_eventos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sge_links_externos_sge_usuarios1`
    FOREIGN KEY (`salvoPor`)
    REFERENCES `SGE`.`sge_usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SGE`.`sge_unidades_eventos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SGE`.`sge_unidades_eventos` ;

CREATE TABLE IF NOT EXISTS `SGE`.`sge_unidades_eventos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idUnidades` INT NOT NULL,
  `idEventos` INT NOT NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  `salvoPor` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_sge_unidades_eventos_sge_unidades1_idx` (`idUnidades` ASC),
  INDEX `fk_sge_unidades_eventos_sge_eventos1_idx` (`idEventos` ASC),
  INDEX `fk_sge_unidades_eventos_sge_usuarios1_idx` (`salvoPor` ASC),
  CONSTRAINT `fk_sge_unidades_eventos_sge_unidades1`
    FOREIGN KEY (`idUnidades`)
    REFERENCES `SGE`.`sge_unidades` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sge_unidades_eventos_sge_eventos1`
    FOREIGN KEY (`idEventos`)
    REFERENCES `SGE`.`sge_eventos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sge_unidades_eventos_sge_usuarios1`
    FOREIGN KEY (`salvoPor`)
    REFERENCES `SGE`.`sge_usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SGE`.`sge_eventos_participantes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SGE`.`sge_eventos_participantes` ;

CREATE TABLE IF NOT EXISTS `SGE`.`sge_eventos_participantes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idEventos` INT NOT NULL,
  `idUsuarios` INT NOT NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_sge_eventos_participantes_sge_eventos1_idx` (`idEventos` ASC),
  INDEX `fk_sge_eventos_participantes_sge_usuarios1_idx` (`idUsuarios` ASC),
  CONSTRAINT `fk_sge_eventos_participantes_sge_eventos1`
    FOREIGN KEY (`idEventos`)
    REFERENCES `SGE`.`sge_eventos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sge_eventos_participantes_sge_usuarios1`
    FOREIGN KEY (`idUsuarios`)
    REFERENCES `SGE`.`sge_usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
